version: '3.8'
services:
  cloud-weather-postgres:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_DATABASE=cloud_weather_dev
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Postgres6367
    ports:
      - '5432:5432'
    volumes: 
      - postgres-data:/data/db
    networks:
      - cloud-weather-services
volumes:
  postgres-data:

networks:
  cloud-weather-services:
    driver: bridge